# 服务配置
server:
  # 服务端口号
  port: 9088
  # 服务路径前缀
  context-path: /v1
  # 是否启用网页控制台（设为false后不会加载前端网页文件）
  console-enable: true
  # 任务执行时间锁，单位毫秒（代表500ms内不会重复执行同一个任务）
  executed-lock-time: 500
# 数据库配置
db:
  # 数据库链接（指定一个新建的MySQL数据库即可，会自动建表）
  dsn: root:123456@tcp(127.0.0.1:3306)/small_scheduler?charset=utf8mb4&parseTime=True&loc=Local
# 日志配置
log:
  # 日志文件存储地址
  path: ./logs/serve.log
  # 单个日志文件最大容量（单位：mb）
  max-size: 1
  # 日志文件存活时间（单位：天）
  max-age: 7
  # 最多可以存在多少个副日志文件
  max-backups: 1000